version: '3.7'

services:
  movie_service:
    build: ./movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service/:/app/
    ports:
      - 8001:8000
    environment:
      - MOVIE_DATABASE_URL=postgresql://${MOVIE_DB_USERNAME}:${MOVIE_DB_PASSWORD}@movie_db:5432/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - movie_db


  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=${MOVIE_DB_USERNAME}
      - POSTGRES_PASSWORD=${MOVIE_DB_PASSWORD}
      - POSTGRES_DB=movie_db_dev
    ports:
      - 5433:5432

  cast_service:
    build: ./cast_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast_service:/app/
    ports:
      - 8002:8000
    environment:
      - CAST_DATABASE_URL=postgresql://${CAST_DB_USERNAME}:${CAST_DB_PASSWORD}@cast_db:5432/cast_db_dev
    depends_on:
      - cast_db


  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=${CAST_DB_USERNAME}
      - POSTGRES_PASSWORD=${CAST_DB_PASSWORD}
      - POSTGRES_DB=cast_db_dev
    ports:
      - 5434:5432
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

volumes:
  postgres_data_movie:
  postgres_data_cast:
